apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jira.app.redhat.com
spec:
  group: app.redhat.com
  names:
    kind: Jira
    listKind: JiraList
    plural: jiras
    singular: jira
  scope: Namespaced
  version: v1alpha1
