apiVersion: app.redhat.com/v1alpha1
kind: Jira
metadata:
  name: jira-ingress
  labels:
    example: jira-ingress
spec:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    host: jira-ingress.example.com
    path: "/"
    secretName: jira-ingress-secret
    tls: true
